[package]
name = "rust_multithread"
version = "0.0.1"
authors = [ "Masator Hori <rillomas@gmail.com>" ]

[dependencies]
rand = "0.3.8"
bincode = "0.3.0"
rustc-serialize = "0.3"

[[bin]]
name = "rust_multithread"
